version: '3.8'

services:
  whatsapp-backend:
    build:
      context: .
      dockerfile: Dockerfile
      # Enable BuildKit for faster builds
      args:
        BUILDKIT_INLINE_CACHE: 1
      # Use cache from previous builds
      cache_from:
        - whatsapp-backend:latest
    image: whatsapp-backend:latest
    container_name: whatsapp-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - CHROME_BIN=/usr/bin/chromium-browser
      - CHROME_PATH=/usr/bin/chromium-browser
    volumes:
      # Persistent storage for sessions and data
      - whatsapp_sessions:/app/sessions
      - whatsapp_logs:/app/logs
      - whatsapp_tokens:/app/tokens
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - whatsapp-network

volumes:
  whatsapp_sessions:
    driver: local
  whatsapp_logs:
    driver: local
  whatsapp_tokens:
    driver: local

networks:
  whatsapp-network:
    driver: bridge
