[build]
builder = "dockerfile"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"
CHROME_BIN = "/usr/bin/chromium-browser"
CHROME_PATH = "/usr/bin/chromium-browser"

# Persistent volume configuration
[volumes]
tokens = "/app/tokens"
logs = "/app/logs"
sessions = "/app/sessions"
